
DEPTOS_SGR = ['Antioquia',
 'Atlántico',
 'BOGOTÁ D.C.',
 'Bolívar',
 'Boyacá',
 'Caldas',
 'Caquetá',
 'Cauca',
 'Cesar',
 'Córdoba',
 'Cundinamarca',
 'Chocó',
 'Huila',
 'La Guajira',
 'Magdalena',
 'Meta',
 'Nariño',
 'Norte De Santander',
 'Quindío',
 'Risaralda',
 'Santander',
 'Sucre',
 'Tolima',
 'Valle Del Cauca',
 'Arauca',
 'Casanare',
 'Putumayo',
 'Archipiélago de San Andrés',
 'Amazonas',
 'Guainía',
 'Guaviare',
 'Vaupés',
 'Vichada']

DIC_COLORES = {'verde':["#009966"],
               'ro_am_na':["#FFE9C5", "#F7B261","#D8841C", "#dd722a","#C24C31", "#BC3B26"],
               'az_verd': ["#CBECEF", "#81D3CD", "#0FB7B3", "#009999"],
               'ax_viol': ["#D9D9ED", "#2F399B", "#1A1F63", "#262947"],
               'ofiscal': ["#F9F9F9", "#2635bf"]}

DEPTOS_PRES = ['CAUCA',
 'BOYACÁ',
 'BOLÍVAR',
 'SANTANDER',
 'ANTIOQUIA',
 'META',
 'TOLIMA',
 'ATLÁNTICO',
 'NARIÑO',
 'CÓRDOBA',
 'CALDAS',
 'CUNDINAMARCA',
 'VALLE DEL CAUCA',
 'NORTE DE SANTANDER',
 'HUILA',
 'RISARALDA',
 'CAQUETÁ',
 'PUTUMAYO',
 'CESAR',
 'SUCRE',
 'CASANARE',
 'AMAZONAS',
 'CHOCÓ',
 'LA GUAJIRA',
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
 'GUAVIARE',
 'QUINDIO',
 'VICHADA',
 'MAGDALENA',
 'ARAUCA',
 'VAUPÉS',
 'BOGOTÁ, D.C.',
 'GUAINÍA']

DIC_DEPTOS = {19: 'CAUCA',
 15: 'BOYACÁ',
 13: 'BOLÍVAR',
 68: 'SANTANDER',
 5: 'ANTIOQUIA',
 50: 'META',
 73: 'TOLIMA',
 8: 'ATLÁNTICO',
 52: 'NARIÑO',
 23: 'CÓRDOBA',
 17: 'CALDAS',
 25: 'CUNDINAMARCA',
 76: 'VALLE DEL CAUCA',
 54: 'NORTE DE SANTANDER',
 41: 'HUILA',
 66: 'RISARALDA',
 18: 'CAQUETÁ',
 86: 'PUTUMAYO',
 20: 'CESAR',
 70: 'SUCRE',
 85: 'CASANARE',
 91: 'AMAZONAS',
 27: 'CHOCÓ',
 44: 'LA GUAJIRA',
 88: 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
 95: 'GUAVIARE',
 63: 'QUINDIO',
 99: 'VICHADA',
 47: 'MAGDALENA',
 81: 'ARAUCA',
 97: 'VAUPÉS',
 11: 'BOGOTÁ, D.C.',
 94: 'GUAINÍA'}